# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: Docker@2
  displayName: 'Docker Login'
  inputs:
    containerRegistry: 'vs-dockerhub'
    command: 'login'

- task: Docker@2
  displayName: 'Docker Build Image'
  inputs:
    containerRegistry: 'vs-dockerhub'
    repository: 'vinodta123'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: 'third'

- task: Docker@2
  displayName: 'Docker Push Image'
  inputs:
    containerRegistry: 'vs-dockerhub'
    repository: 'vinodta123'
    command: 'push'
    tags: 'third'
