apiVersion: v1
kind: Service
metadata:
  name: citizendetailapi
  labels:
    app: citizendetailapi
spec:
  selector:
      app: citizendetailapi
  ports:
     - name: http
       port: 8080
       nodePort: 30064
  type: LoadBalancer